# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"
    main: ./cmd/genlog/main.go

archives:
  - formats: ["binary"]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

release:
  draft: false
  prerelease: auto
  mode: append

changelog:
  groups:
    - title: Added
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Fixed
      regexp: "^.*fix\\((?!deps\\))[(\\w)]*:+.*$"
      order: 1
    - title: Dependency Updates
      regexp: "^.*\\(deps\\)*:+.*$"
      order: 2
    - title: Other
      order: 999
