# Example configuration for genlog
# All configuration configuration can be viewed in the README.md
seed: 12345

templates:
  - template: '{{FormattedDate "2006-01-02T15:04:05.000Z07:00"}} [{{level}}] {{username}} - {{message}}'
    weight: 5
  - template: '{{FormattedDate "Jan 2 15:04:05"}} {{level}} [{{service}}] {{IPv4Address}} {{username}}: {{message}}'
    weight: 3
  - template: '{"timestamp":"{{FormattedDate "2006-01-02T15:04:05.000Z07:00"}}","level":"{{level}}","service":"{{service}}","message":"{{message}}","user":"{{username}}","ip":"{{ipv4}}"}'
    weight: 2

# Custom types that can be referenced in templates
custom_types:
  level:
    - INFO
    - WARNING
    - ERROR
    - DEBUG
    - TRACE
  service:
    - API
    - AUTH
    - DATABASE
    - CACHE
    - FRONTEND
  username:
    - admin
    - system
    - app
    - service_account
    - anonymous
  message:
    - "User authenticated successfully"
    - "Failed login attempt - invalid credentials"
    - "Permission denied to resource"
    - "Resource accessed successfully"
    - "API rate limit exceeded"
    - "Database connection timeout"
    - "Cache invalidation completed"
    - "Request processed in 235ms"
